## What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy stands for Numerical Python.

## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
!pip install numpy

In [6]:
import numpy as np
print(np.__version__)

1.24.3


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [8]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [9]:
# create an array method 1
import numpy as np
arr1 = np.array([1, 3, 5, 7,9])
print(arr1)
print(type(arr1))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [10]:
# create an array method 2
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Why it is useful?
l=range(1000)
%timeit [i**2 for i in l]

132 µs ± 9.35 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2

2.1 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
# Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [18]:
print(arr[0][0][0][0][2])

3


In [19]:
arr = np.array([[1, 2, 3, 4],[5,6,7,8]])
print(arr[1,1])

6


In [20]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [24]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]])
print(arr[1, -1])

[ 6  7  8  9 10]


In [25]:
arr.shape

(3, 2, 5)

In [26]:
len(arr)

3

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print(arr[::2])

[2 3 4 5]
[5 6]
[1 3 5 7]


In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [34]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [36]:
arr_2=np.arange(1,10,2)
print(arr_2)

[1 3 5 7 9]


In [37]:
a=np.linspace(0,1,6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [38]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [40]:
# Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [42]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [43]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [44]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [48]:
np.diag(a)

array([1, 2, 3, 4])

## Random function

In [49]:
# create array using random
a=np.random.rand(4)
a

array([0.17820401, 0.85827976, 0.87257202, 0.91934949])

In [51]:
x = np.random.rand(3, 5)

print(x)

[[0.23440364 0.45891892 0.06434135 0.96257467 0.38630617]
 [0.63693683 0.94147001 0.5055664  0.64156744 0.1973083 ]
 [0.91202086 0.38271418 0.40790786 0.75179651 0.88299436]]


In [ ]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

In [52]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[32 83 89 22 11]
 [18 24 98 37 39]
 [14 42 84 41 77]]


In [58]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


In [59]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 7 3 5]
 [3 9 3 9 5]
 [3 9 9 7 7]]


In [60]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [61]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [62]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [63]:
np.shares_memory(a,b)

False

In [64]:
c=a[::2]
c
np.shares_memory(a,c)

True

### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [2]:
# All arithmetic operates elementwise
import numpy as np

a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [2]:
a=np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [8]:
a=np.array([1,2,3,4])
b=np.ones(4)+1
print(a)
print(b)
print(a-b)

[1 2 3 4]
[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [9]:
a*b

array([2., 4., 6., 8.])

In [11]:
c=np.diag([1,2,3,4])
print(c*c)
print("\n")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
a=np.array([1,2,3,4])
b=np.array([4,2,6,4])
a==b

array([False,  True, False,  True])

In [14]:
a>b

array([False, False, False, False])

In [3]:
# array-wise comparisions
a=np.array([1,2,3,4])
b=np.array([4,2,6,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [4]:
np.array_equal(a,c)

True

In [19]:
a=np.array([1,0,1,0],dtype=bool)
b=np.array([0,1,1,1],dtype=bool)
c=np.array([1,0,1,1],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [20]:
np.logical_and(a,c)

array([ True, False,  True, False])

In [5]:
# Trignometric operations
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [6]:
np.log(a)

C:\Users\hp\AppData\Local\Temp\ipykernel_200176\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [7]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [8]:
a=np.array([1,2,3,4])
np.sum(a)

10

In [9]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [10]:
x.sum(axis=0)

array([3, 3])

In [11]:
x.sum(axis=1)

array([2, 4])

In [12]:
x=np.arange(1,10)
x.min()

1

In [13]:
x.max()

9

In [14]:
# index of minimum element
x.argmin()

0

In [15]:
# index of maximum element
x.argmax()

8

In [16]:
np.all([1,1,1,1])

True

In [17]:
np.all([True,True,True,True])

True

In [18]:
np.any([True,True,False,False])

True

In [21]:
a=np.zeros((50,50))
np.any(a != 0)

False

In [22]:
np.all(a==a)

True

In [23]:
a=np.array([1,2,3,2])
b=np.array([1,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

In [24]:
a=np.array([1,2,3,1])
b=np.array([[1,2,3],[5,6,1]])
a.mean()

1.75

In [45]:
np.median(a)

1.5

In [25]:
np.median(b,axis=-1) #last axis

array([2., 5.])

In [26]:
a.std()

0.82915619758885

In [29]:
# load data into numpy array object
data=np.loadtxt('sample.txt')

In [30]:
data

array([[1.e+00, 2.e+00, 3.e+00, 4.e+00],
       [1.e+01, 2.e+01, 3.e+01, 4.e+01],
       [1.e+02, 2.e+02, 3.e+02, 4.e+02],
       [1.e+03, 2.e+03, 3.e+03, 4.e+03],
       [1.e+04, 2.e+04, 3.e+04, 4.e+04]])

In [31]:
a,b,c,d=data.T # Columns are variables

In [32]:
print(a)
print(b)
print(c)
print(d)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[2.e+00 2.e+01 2.e+02 2.e+03 2.e+04]
[3.e+00 3.e+01 3.e+02 3.e+03 3.e+04]
[4.e+00 4.e+01 4.e+02 4.e+03 4.e+04]


In [33]:
data[:,:]

array([[1.e+00, 2.e+00, 3.e+00, 4.e+00],
       [1.e+01, 2.e+01, 3.e+01, 4.e+01],
       [1.e+02, 2.e+02, 3.e+02, 4.e+02],
       [1.e+03, 2.e+03, 3.e+03, 4.e+03],
       [1.e+04, 2.e+04, 3.e+04, 4.e+04]])

In [34]:
p=data[:,1:]
p

array([[2.e+00, 3.e+00, 4.e+00],
       [2.e+01, 3.e+01, 4.e+01],
       [2.e+02, 3.e+02, 4.e+02],
       [2.e+03, 3.e+03, 4.e+03],
       [2.e+04, 3.e+04, 4.e+04]])

In [35]:
np.median(p,axis=0)

array([200., 300., 400.])

In [36]:
p.std(axis=0)

array([ 7813.79481686, 11720.69222529, 15627.58963372])

In [37]:
np.argmax(p, axis=1)

array([2, 2, 2, 2, 2], dtype=int64)

In [39]:
arr=np.array([1,2,3,4])
a=np.tile(arr,(3,1))
print(a)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [40]:
a=a.T
print(a)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [42]:
c=np.array([1,1,1])

In [43]:
a+c

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [44]:

d=np.array([[1],[0],[1],[0]])
d

array([[1],
       [0],
       [1],
       [0]])

In [46]:
c+d

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [47]:
a=np.arange(0,40,10)
a.shape

(4,)

In [48]:
a=a[:,np.newaxis] # adds a new axis -> 2d array
a.shape

(4, 1)

In [49]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [50]:
b=a.T
b

array([[ 0, 10, 20, 30]])

In [51]:
a+b

array([[ 0, 10, 20, 30],
       [10, 20, 30, 40],
       [20, 30, 40, 50],
       [30, 40, 50, 60]])

In [52]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [54]:
a=np.array([[1,2,3],[4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [91]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [56]:
b=a.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
a=np.arange(4*3*2).reshape(4,3,2)
a
print("order",a.shape)

order (4, 3, 2)


In [58]:
a=np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [100]:
a=np.arange(4)
a.resize((8,1))
a

array([[0],
       [1],
       [2],
       [3],
       [0],
       [0],
       [0],
       [0]])

In [59]:
b=a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [60]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [61]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [105]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.argsort(arr))

[2 3 1 0]
